### ISSUE TITLE
[BUTTON IDEA]: Rounded Corners Button

### ISSUE THREAD

**Issue by ThePotato10** [sButtons/sbuttons#1379]
**1. Name of button**: Rounded Corners Button

**2. Description**: The current rounded button is more pill shaped than I'd like, and so I'm proposing a new button type called the rounded corners button. This button isn't pill shaped, but instead has rounded corners. `border-radius: 10px;` would probably work fine.

**3. Button Type (Animated, Special, etc...)**: Basic

**4. Will you work on it?**: Yes

**Comment by shahednasser** [comment]
Hello @ThePotato10 thank you for your idea! I suggest instead of adding a new button, we can add helper classes that can change the `border-radius` of rounded buttons. Let me know if this approach suits you and if you can work on it.

**Comment by ThePotato10** [comment]
That sounds great actually. I'd be happy to work on this. Are you thinking of something kind of like Tailwind for the helper classes?

**Comment by shahednasser** [comment]
yea something like that but let's make it simple. Maybe adding a few classes like `rounded-5`, `rounded-10`, etc...

We can also make this a mixin in LESS so that anyone that's using the source files can extend them to add their own variations.

I'll assign you to this issue. Let me know if you need any help.
