### ISSUE TITLE
bundle the npm run clean-css command along with npm start

### ISSUE THREAD

**Issue by mrSidSat** [sButtons/sbuttons#1519]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
run both the commands npm run compile and npm run clean-css (which would look for changes in sbuttons.css) simultaneously with the command npm start which would indeed facilitate faster development.

**Additional notes**
I would like to work on this.

**Comment by shahednasser** [comment]
Hi @mrSidSat that's a nice suggestion.

I think instead of changing `start` we should add a new script `build` which would perform both commands.

You need to also change the contributing guidelines in this part:

https://github.com/sButtons/sbuttons/blob/d423a5cda790660588e13921f6841d1772be7e23/CONTRIBUTING.md#L47-L50

Replace it with just using the new build command.

I'll assign you for this
