### ISSUE TITLE
Atom Button

### ISSUE THREAD

**Issue by shahednasser** [sButtons/sbuttons#422]
**1. Name of button**: Atom Button

**2. Description**: A button with a moving atom on its border on hover.

**3. Button Type (Animated, Special, etc...)**: Animated

**4. Will you work on it?**: no

**submitted by**: @Maitryee-Choudhary

**Comment by diptigautam** [comment]
Hi, I'd like to work on this!

**Comment by shahednasser** [comment]
Sure @diptigautam I'll assign you

**Comment by Summer-source** [comment]
I'd like to work on this!

**Comment by shahednasser** [comment]
someone is assigned to this issue @Summer-source

**Comment by diptigautam** [comment]
Hi @shahednasser I completed the tasks but I can't test it because on merging with the latest versions, I can't get npm to start, and the inital npm install is giving me errors as well. JavaScript is not my forte, so I'm not sure how to solve it. 

Would you suggest that I go ahead and create a PR anyway? (The CSS works fine on codepen, and I have also made all the necessary changes in the required spaces.).

**Comment by shahednasser** [comment]
can you please show me the error you are getting? Also is your repo up to date with this one?

**Comment by diptigautam** [comment]
Hii, yes it was up to date, but `npm install` was failing, and now it's working after I tried installing the failed packages one by one manually.
A few things are remaining, and I'll submit a PR!
